projects:
  MPC-AgentState:
    schemaPath: src/graphql/schema.json
    includes:
      - mpc_appsync
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: us-east-1
        apiId: hjevdbsbmrabdktzzw3k3ccjdu
        maxDepth: 2
